version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - transcendence
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=backend
    expose:
      - "3001"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - transcendence
    expose:
      - "3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    networks:
      - transcendence
  
  # nginx:
  #   build:
  #     context: nginx
  #   container_name: nginx
  #   restart: always
  #   tty: true
  #   ports:
  #     - "8000:80"
  #   networks:
  #     - transcendence
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
  #   depends_on:
  #     - frontend
  #     - backend

networks:
  transcendence:
    driver: bridge