version: '3'

services:
    db:
        image: postgres:14
        container_name: db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
            - ./backend/.env
        networks:
            - transcendence_network
        restart: always

    frontend:
        container_name: frontend
        build: ./frontend
        env_file:
            - .env
            - .env.private
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        depends_on:
            - db
        networks:
            - transcendence_network
        restart: unless-stopped
    
    backend:
        container_name: backend
        build: ./backend
        env_file:
            - .env
            - ./backend/.env
            - .env.private
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        depends_on:
            - db
            - frontend
        networks:
            - transcendence_network
        restart: unless-stopped

    prisma-studio:
        container_name: prisma-studio
        build:
            context: ./backend
            dockerfile: Dockerfile.studio
        env_file:
            - ./backend/.env
        ports:
            - "5555:5555"
        depends_on:
            - db
            - backend
            - frontend
        networks:
            - transcendence_network
        restart: unless-stopped

volumes:
    pgdata:
        name: pgdata

networks:
    transcendence_network:
        driver: bridge
